### ISSUE TITLE
[TASK] 랜딩페이지 제작

### ISSUE THREAD

**Issue by jo-seungho** [codestates/PIC.#1]
### ISSUE

- 그룹 : `client` 
- 타입 : `feature`
- 상세설명 : 첫 방문시 보여질 화면 구성과 간략한 사이트의 정보를 담고있습니다.

### TODO

- [ ]  서비스 소개 문구 작성
- [ ]  화면 디자인
- [ ]  스크롤시 화면 렌더링 기능
- [ ]  시작하기 버튼으로 게시판 접근

### Labels

- `client`
