### ISSUE TITLE
[TASK] 페이지 전반 CSS 수정

### ISSUE THREAD

**Issue by CHOI-K-ROCK** [codestates/PIC.#127]
### ISSUE

- 그룹 : `client`
- 타입 : `feature`
- 상세설명 : 페이지의 CSS 를 통일감 있게 구성합니다.

### TODO

- [ ]  모달의 백드롭이 정상적으로 작동 가능하게끔 CSS를 수정합니다.
- [ ] 기본 폰트로 사용될 웹 폰트를 적용합니다.
- [ ] 아직 CSS 가 적용되지 않은 페이지들의 CSS 를 완성합니다.

### Labels

-  `client` , `high`
