### ISSUE TITLE
[TASK] 컴포넌트 및 페이지 디렉토리 정리

### ISSUE THREAD

**Issue by CHOI-K-ROCK** [codestates/PIC.#128]
### ISSUE

- 그룹 : `client`
- 타입 : `feature`
- 상세설명 : 컴포넌트와 페이지의 디렉토리를 더 상세하게 정리합니다.

### TODO

- [ ]  oauth 를 위한 컴포넌트와 callback 페이지를 oauth 폴더에 정리합니다.
- [ ] 모달 컴포넌트를 modal 폴더로 이동시킵니다.
- [ ] 위치가 변경된 컴포넌트를 사용하는 컴포넌트 내부에서  변경된 경로로 수정합니다.

### Labels

-  `client`, `low`
