### ISSUE TITLE
[TASK] 최종 배포 전 리팩토링

### ISSUE THREAD

**Issue by CHOI-K-ROCK** [codestates/PIC.#129]
### ISSUE

- 그룹 : `client`
- 타입 : `feature`
- 상세설명 : 불필요한 코드와 로직을 수정하거나, console.log 를 정리합니다.

### TODO

- [ ]  불필요한 변수와 상태를 정리합니다.
- [ ] console.log 를 삭제합니다.
- [ ] 로직을 개선 할 수 있다면 시도해봅니다.
- [ ] 환경변수로 관리되어야 할 항목이 일반 변수로 관리되고 있지는 않은지 확인합니다.
- [ ] 메타 태그와 파비콘, 아이콘 등을 수정합니다.

### Labels

-  `client`, `high`
