### ISSUE TITLE
[TASK] 확인 모달 컴포넌트 구현

### ISSUE THREAD

**Issue by Lpickle** [codestates/PIC.#13]
### ISSUE

- 그룹 : `client` 
- 타입 : `feature`
- 상세설명 :  오류 발생시 alert 창 대신. 확인 모달 창을 이용하여 필요한 메세지를 작성하여 표시합니다.

### TODO

- [ ]  예, 예 / 아니오 모달을 각각 작성합니다.
- [ ] props 로 내용을 전달받아 모달창에 안내 메시지로 표시합니다.
- [ ] 예 버튼을 누를 때 각 상황에 적합한 함수를 props 로 전달 받고 실행 할 수 있어야합니다. (페이지 이동, 탈퇴, 삭제 등등)
### Labels

- `client`
