### ISSUE TITLE
[TASK] 태그 검색

### ISSUE THREAD

**Issue by jo-seungho** [codestates/PIC.#31]
### ISSUE

- 그룹 : `client` 
- 타입 : `feature`
- 상세설명 : 유저가 직접 태그를 입력하여 검색이 가능합니다

### TODO

- [ ] 검색 창(input)에 단어가 입력되고 (+)버튼을 클릭할 경우 태그 란에 보여집니다
- [ ] 태그 란에 모여있는 각각의 태그들은 삭제가 가능합니다
- [ ] search result 창에서 태그란에 포함되어있는 태그를 가지고 있는 게시물만 렌더링 됩니다 

### Labels

-  `client`, `high`
