### ISSUE TITLE
[TASK] 게시글 작성 컴포넌트 구현

### ISSUE THREAD

**Issue by jo-seungho** [codestates/PIC.#42]
### ISSUE

- 그룹 : `client` 
- 타입 : `feature`
- 상세설명 : 사진과 위치 , 제목, 태그 및 설명을 작성 할 수 있습니다

### TODO

- [ ] 이미지와 좌표의 위치가 저장되어야 합니다
- [ ] 제목을 입력 할 수 있어야 합니다
- [ ] 태그를 다중 선택 할 수 있어야 합니다
- [ ] 태그 버튼(toggle) 구현
- [ ] 태그를 직접 입력하여 추가 및 삭제가 가능합니다
- [ ] 사진에 대한 설명을 입력할 수 있습니다

### Labels

-  `client`,`middle`
