### ISSUE TITLE
[TASK] 기본 태그 컴포넌트 작성

### ISSUE THREAD

**Issue by CHOI-K-ROCK** [codestates/PIC.#44]
### ISSUE

- 그룹 : `client`
- 타입 : `feature`
- 상세설명 : 생성된 태그의 모양과 선택여부를 표시하는 컴포넌트를 제작합니다.

### TODO

- [ ] 선택되지 않은 태그는 회색으로 표시되어야 합니다.
- [ ]  선택된 태그의 색상은 무작위로 결정되어야 합니다.
- [ ] props 로 태그의 이름을 받아 표시하여야 하며, 그 길이에 따라 태그의 가로길이가 길어져야 합니다.

### Labels

-  `client`, `low`
