### ISSUE TITLE
[TASK] 상단 이동 컴포넌트 구현

### ISSUE THREAD

**Issue by jo-seungho** [codestates/PIC.#5]
### ISSUE

- 그룹 : `client` 
- 타입 : `feature`
- 상세설명 : 상단에 고정된 컴포넌트 이동 버튼을 구현합니다

### TODO

- [ ] 경로(path)연결
- [ ] Hover기능 구현
- [ ] 로그인 여부에 따라 연결 경로가 달라집니다(마이페이지/회원가입, 로그인/로그아웃)
- [ ] 내사진, 인기사진, 최신사진, 즐겨찾기, 키워드검색, 태그 검색, 마이페이지/회원가입, 로그인/로그아웃 연결

### Labels

- `client`
