### ISSUE TITLE
[TASK] 게시글 썸네일 컴포넌트 작성

### ISSUE THREAD

**Issue by CHOI-K-ROCK** [codestates/PIC.#54]
### ISSUE

- 그룹 : `client`
- 타입 : `feature`
- 상세설명 : 게시글의 내용을 미리 볼 수 있는 썸네일을 작성합니다.

### TODO

- [ ]  해당 게시글의 사진이 표시되어야 합니다.
- [ ] 해당 게시글의 이름과 올린 이의 닉네임을 표시해야합니다.
- [ ] 해당 게시글을 올린 위치를 가져와 위치를 좌표가 아닌 지명으로 표시 할 수 있어야합니다.(카카오맵 API 이용)
- [ ] 해당 게시글의 좋아요 갯수, 댓글 갯수(optional)를 가져 와 표시 할 수 있어야합니다.

### Labels

-  `client`, `middle`
