### ISSUE TITLE
[TASK] 좋아요 버튼 컴포넌트 구현

### ISSUE THREAD

**Issue by CHOI-K-ROCK** [codestates/PIC.#60]
### ISSUE

- 그룹 : `client` 
- 타입 : `feature`
- 상세설명 : 해당 게시물을 좋아요 눌렀는지에 대한 여부를 표시하며, 버튼을 클릭하여 나의 좋아요에 추가하거나, 제거할 수 있는 컴포넌트를 작성합니다.

### TODO

- [ ] 해당 게시글을 좋아요한 사람중에 내가 포함되어 있는 경우 색상을 가진 도형으로 표시합니다.(아닌 경우 회색으로 표시합니다.)
- [ ] 좋아요 여부가 해당 버튼의 색상으로 즉시 반영되어야 합니다.
- [ ] 버튼을 클릭하는 경우 좋아요 토글 요청을 보내야합니다.

### Labels

-  `client`, `low`
