### ISSUE TITLE
[TASK] Styled-Component 의 ThemeProvider 를 이용한 자주 사용하는 컬러 변수화

### ISSUE THREAD

**Issue by CHOI-K-ROCK** [codestates/PIC.#78]
### ISSUE

- 그룹 : `client` 
- 타입 : `feature`
- 상세설명 :  Styled-Component 의 ThemeProvider 를 이용하여 자주 사용하는 컬러를 전역변수로 사용합니다.

### TODO

- [ ]  최상위 컴포넌트를 ThemeProvider 감싸 하위 컴포넌트에 변수를 전달 할 수 있게합니다.
- [ ] theme.js 를 만들어 원하는 색상들을 변수명에 저장합니다.
- [ ] 기존에 hexcode 로 작성된 내용들을 수정합니다.

### Labels

-  `client`, `low`
