### ISSUE TITLE
[TASK] 버튼 컴포넌트 분리

### ISSUE THREAD

**Issue by CHOI-K-ROCK** [codestates/PIC.#80]
### ISSUE

- 그룹 : `client` 
- 타입 : `feature`
- 상세설명 : 나의 정보 수정페이지에 작성된 버튼 컴포넌트를 재사용이 가능한 개별 컴포넌트로 분리합니다.

### TODO

- [ ] 나의 정보 수정페이지의 버튼 컴포넌트를 새로운 컴포넌트 파일로 이동합니다.
- [ ] 기존에 작성되었던 나의 정보 수정페이지의 버튼을 해당 컴포넌트로 다시 작성합니다.
- [ ] props 를 이용하여 너비와 버튼의 내용 이름, 버튼 색상을 수정 할 수 있게 합니다.(선택)

### Labels

-  `client`, `low`
