### ISSUE TITLE
[TASK] 게시글 작성 및 수정 페이지 이미지 미리보기 로직 변경하기

### ISSUE THREAD

**Issue by CHOI-K-ROCK** [codestates/PIC.#98]
### ISSUE

- 그룹 : `client`
- 타입 : `feature`
- 상세설명 : 이미지를 백그라운드 속성이 아닌 img 태그로 변경합니다.

### TODO

- [ ] 기존 컨테이너에 img 태그를 이용하여 이미지를 삽입합니다.
- [ ] 이미지의 크기는 컨테이너 크기에 맞게 contain 해야합니다.
- [ ] onload 이벤트를 이용하여 로딩 상태를 제어하고, 이미지의 로딩이 전부 끝나 불러와진 경우에 해당 상태를 변경합니다.

### Labels

-  `client`, `middle`
